version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/docker/my-db:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - /home/docker/postgres-data:/var/lib/postgresql/data  
  
  maildev:
    image: djfarrelly/maildev
    container_name: maildev
    restart: always
    ports: 
      - "1025:25"
      - "1080:80"
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports: 
      - "8080:8080"
